FROM rohmhatre/yaksh


RUN  mkdir -p /Sites/online_test 

VOLUME /Sites/online_test

ADD ./online_test/requirements/requirements-* /tmp/

RUN cd /Sites/online_test && pip3 install -r /tmp/requirements-py3.txt 

ADD Files/000-default.conf /etc/apache2/sites-enabled/

ADD Files/Docker-script.sh /Sites/Docker-script.sh

EXPOSE 80

WORKDIR /Sites/online_test

CMD [ "/bin/bash" , "/Sites/Docker-script.sh" ] 
